### alle!
GET http://localhost:3000/uhren
### dummy uhr
GET http://localhost:3000/uhren/64c9369e9406cbd9c5ffba8d
### error 404
GET http://localhost:3000/uhren/64c92e83aa83214525332523a
###
POST http://localhost:3000/uhren
Content-Type: application/json

{
   "user": "Georg",
   "uhr": "dummy",
   "dateMeasured": "2023-08-01T16:04:11.077Z",
   "offsetSecs": -5
}
### patch
PATCH http://localhost:3000/uhren/64c9369e9406cbd9c5ffba8d
Content-Type: application/json

{
   "user": "Teresa",
   "uhr": "dummy",
   "dateMeasured": "2023-08-12T16:04:11.077Z",
   "offsetSecs": -12
}

### delete
DELETE http://localhost:3000/uhren/64c930cbaa8b93d759c2b15e