### alle!
GET http://localhost:16631/uhren
### nur die liste
GET http://localhost:16631/uhren/liste
### dummy uhr
GET http://localhost:16631/uhren/id/64e05b4c1576e8a621fe0e57
### error 404
GET http://localhost:16631/uhren/id/64c92e83aa83214525332523a
###
GET http://localhost:16631/uhren/daten/Tante%20Ju
### NEW ENTRY
POST http://localhost:16631/uhren
Content-Type: application/json

{
   "user": "Georg",
   "uhr": "Presage",
   "dateMeasured": "2023-08-31T09:04:11.077Z",
   "offsetSecs": -3
}
### patch
PATCH http://localhost:16631/uhren/id/64e05d761576e8a621fe0e5d
Content-Type: application/json

{
   "user": "Teresa",
   "uhr": "dummies",
   "dateMeasured": "2023-08-12T16:04:11.077Z",
   "offsetSecs": -12
}

### delete
DELETE http://localhost:16631/uhren/id/64e05b4c1576e8a621fe0e57