###
PATCH /watchtracker/auth/measure/clwkzdyts0003rdx3ghrckia6 HTTP/1.1
Host: 0.0.0.0:16631
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0
Accept: */*
Accept-Language: de,en;q=0.5
Accept-Encoding: gzip, deflate
HX-Request: true
HX-Trigger-Name: value
HX-Current-URL: http://0.0.0.0:16631/watchtracker
Content-Type: application/x-www-form-urlencoded
Content-Length: 7
Origin: http://0.0.0.0:16631
Connection: keep-alive
Cookie: watchtracker_sid=s%3AGrz1szpzNSpZERm9pdhiq0CFBtrDNMt9.djlK%2B3tDrAvLpI1cDAagaVXL7zB7ogW%2BH32QVZzxBeU
Referer: http://0.0.0.0:16631/watchtracker

value=3

###
### alle!
GET http://localhost:16631/watchtracker
### nur die liste
GET http://localhost:16631/watchtracker/liste
### dummy uhr
GET http://localhost:16631/watchtracker/id/64e05b4c1576e8a621fe0e57
### error 404
GET http://localhost:16631/watchtracker/id/64c92e83aa83214525332523a
###
GET http://localhost:16631/watchtracker/daten/Tante%20Ju
### Logout-full
POST http://localhost:16631/watchtracker/logout

### Logout-hx
POST http://localhost:16631/watchtracker/logout
HX-REQUEST: true

### NEW ENTRY
POST http://localhost:16631/watchtracker
Content-Type: application/json

{
   "user": "Georg",
   "uhr": "Presage",
   "dateMeasured": "2023-08-31T09:04:11.077Z",
   "offsetSecs": -3
}
### patch
PATCH http://localhost:16631/watchtracker/id/64e05d761576e8a621fe0e5d
Content-Type: application/json

{
   "user": "Teresa",
   "uhr": "dummies",
   "dateMeasured": "2023-08-12T16:04:11.077Z",
   "offsetSecs": -12
}

### delete
DELETE http://localhost:16631/watchtracker/id/64e05b4c1576e8a621fe0e57